
db:
  dsn: "dbuser:dbpwd@tcp(localhost:3306)/db_name?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 60 # 最大存活时间，单位：分钟
  check_interval: 3 # Ping检测时间间隔，单位：分钟

auth:
  - source: github
    client_id: Ov23csdx3vwmihIIN
    client_secret: 781dc68224800827b2131ecae332130ff8a39469
    callback_uri: "http://127.0.0.1:8080/auth/github_callback"

jwt:
  sign_key: 781dc68224872827b2131e4ae332130ff8a39469

log:
  - writer: console
    formatter: json
    level: DEBUG
  - writer: file
    formatter: json
    level: DEBUG
    format_config:
      time_fmt: "2006-01-02 15:04:05.000"
    write_config:
      log_path: "./run.log"
      max_size: 10
      max_age: 30
      compress: true